# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-27 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_article_comment_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True)),
                ('img', models.ImageField(upload_to='img')),
            ],
            options={
                'db_table': 'ImageStore',
            },
        ),
    ]
