# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-27 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_imagestore'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('article_id', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='ImageStore',
        ),
    ]
