# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-27 13:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_auto_20171227_2133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='collector_id',
        ),
    ]
