# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-27 14:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_auto_20171227_2139'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='collect',
            table='collect',
        ),
    ]
