# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-28 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_auto_20171227_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='icon',
            field=models.CharField(default='default.png', max_length=20),
        ),
    ]
